CREATE TABLE public.account (
    currency character varying(3) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    owner_user_id bigint NOT NULL,
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT account_type_check CHECK (((type)::text = ANY ((ARRAY['ASSET'::character varying, 'LIABILITY'::character varying, 'INCOME'::character varying, 'EXPENSE'::character varying, 'EQUITY'::character varying])::text[])))
);

CREATE TABLE public.account_current_balance (
    raw_balance_minor bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    account_id uuid NOT NULL
);

CREATE TABLE public.category_tag (
    color character varying(7),
    created_at timestamp(6) with time zone NOT NULL,
    owner_user_id bigint NOT NULL,
    id uuid NOT NULL,
    name character varying(255) NOT NULL
);

CREATE TABLE public.currency (
    code character varying(3) NOT NULL,
    minor_unit smallint NOT NULL,
    name character varying(255) NOT NULL
);

CREATE TABLE public.household (
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    id uuid NOT NULL,
    name character varying(255) NOT NULL
);

CREATE TABLE public.household_account_share (
    shared_at timestamp(6) with time zone NOT NULL,
    shared_by bigint NOT NULL,
    account_id uuid NOT NULL,
    household_id uuid NOT NULL
);

CREATE TABLE public.household_member (
    invited_at timestamp(6) with time zone,
    invited_by bigint,
    joined_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    household_id uuid NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT household_member_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'ADMIN'::character varying, 'MEMBER'::character varying])::text[]))),
    CONSTRAINT household_member_status_check CHECK (((status)::text = ANY ((ARRAY['INVITED'::character varying, 'ACTIVE'::character varying])::text[])))
);

CREATE TABLE public.ledger_split (
    amount_minor bigint NOT NULL,
    account_id uuid NOT NULL,
    category_tag_id uuid,
    id uuid NOT NULL,
    txn_id uuid NOT NULL,
    side character varying(255) NOT NULL,
    CONSTRAINT ledger_split_side_check CHECK (((side)::text = ANY ((ARRAY['DEBIT'::character varying, 'CREDIT'::character varying])::text[])))
);

CREATE TABLE public.ledger_txn (
    currency character varying(3) NOT NULL,
    txn_date date NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by_user_id bigint NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    household_id uuid,
    id uuid NOT NULL,
    description character varying(255) NOT NULL
);

CREATE TABLE public.user_roles (
    id bigint NOT NULL,
    user_id bigint,
    role character varying(255)
);

ALTER TABLE public.user_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    avatar_path character varying(255),
    email character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL
);

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.account_current_balance
    ADD CONSTRAINT account_current_balance_pkey PRIMARY KEY (account_id);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.category_tag
    ADD CONSTRAINT category_tag_owner_user_id_name_key UNIQUE (owner_user_id, name);

ALTER TABLE ONLY public.category_tag
    ADD CONSTRAINT category_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_pkey PRIMARY KEY (code);

ALTER TABLE ONLY public.household_account_share
    ADD CONSTRAINT household_account_share_pkey PRIMARY KEY (account_id, household_id);

ALTER TABLE ONLY public.household_member
    ADD CONSTRAINT household_member_pkey PRIMARY KEY (user_id, household_id);

ALTER TABLE ONLY public.household
    ADD CONSTRAINT household_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ledger_split
    ADD CONSTRAINT ledger_split_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ledger_txn
    ADD CONSTRAINT ledger_txn_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT uk_account_owner_type_currency_name UNIQUE (owner_user_id, type, currency, name);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

CREATE INDEX idx_account_current_balance_updated_at ON public.account_current_balance USING btree (updated_at);

CREATE INDEX idx_account_owner ON public.account USING btree (owner_user_id);

CREATE INDEX idx_ledger_txn_creator ON public.ledger_txn USING btree (created_by_user_id);

CREATE INDEX idx_ledger_txn_date ON public.ledger_txn USING btree (txn_date);

CREATE INDEX idx_ledger_txn_household ON public.ledger_txn USING btree (household_id);

CREATE INDEX idx_ledger_txn_household_date ON public.ledger_txn USING btree (household_id, txn_date);

CREATE INDEX idx_member_household ON public.household_member USING btree (household_id);

CREATE INDEX idx_member_household_status ON public.household_member USING btree (household_id, status);

CREATE INDEX idx_member_user_status ON public.household_member USING btree (user_id, status);

CREATE INDEX idx_split_account ON public.ledger_split USING btree (account_id);

CREATE INDEX idx_split_txn ON public.ledger_split USING btree (txn_id);

ALTER TABLE ONLY public.ledger_split
    ADD CONSTRAINT fk_ledger_split_txn FOREIGN KEY (txn_id) REFERENCES public.ledger_txn(id);

ALTER TABLE ONLY public.ledger_split
    ADD CONSTRAINT fk_ledger_split_account FOREIGN KEY (account_id) REFERENCES public.account(id);

ALTER TABLE ONLY public.household_member
    ADD CONSTRAINT fk_household_member_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.category_tag
    ADD CONSTRAINT fk_category_tag_owner FOREIGN KEY (owner_user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.ledger_split
    ADD CONSTRAINT fk_ledger_split_category_tag FOREIGN KEY (category_tag_id) REFERENCES public.category_tag(id);

ALTER TABLE ONLY public.account_current_balance
    ADD CONSTRAINT fk_account_current_balance_account FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ledger_txn
    ADD CONSTRAINT fk_ledger_txn_household FOREIGN KEY (household_id) REFERENCES public.household(id);

ALTER TABLE ONLY public.ledger_txn
    ADD CONSTRAINT fk_ledger_txn_currency FOREIGN KEY (currency) REFERENCES public.currency(code);

ALTER TABLE ONLY public.household_member
    ADD CONSTRAINT fk_household_member_household FOREIGN KEY (household_id) REFERENCES public.household(id);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fk_account_currency FOREIGN KEY (currency) REFERENCES public.currency(code);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.household_account_share
    ADD CONSTRAINT fk_household_account_share_account FOREIGN KEY (account_id) REFERENCES public.account(id);

ALTER TABLE ONLY public.household_account_share
    ADD CONSTRAINT fk_household_account_share_household FOREIGN KEY (household_id) REFERENCES public.household(id);

ALTER TABLE ONLY public.ledger_txn
    ADD CONSTRAINT fk_ledger_txn_created_by FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.household_member
    ADD CONSTRAINT fk_household_member_invited_by FOREIGN KEY (invited_by) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fk_account_owner FOREIGN KEY (owner_user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.household
    ADD CONSTRAINT fk_household_created_by FOREIGN KEY (created_by) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.household_account_share
    ADD CONSTRAINT fk_household_account_share_shared_by FOREIGN KEY (shared_by) REFERENCES public.users(user_id);
