spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/pocketr_db
    username: pocketr_user
    password: pocketr_password
  flyway:
    baseline-on-migrate: true

server:
  port: 8081
  servlet:
    session:
      cookie:
        path: /

app:
  security:
    csrf-cookie-path: /

pocketr:
  avatar:
    storage-dir: ${AVATAR_STORAGE_DIR:storage/avatars}
